### PR TITLE
fix: adds menubar to topbar's ul

### LINKED ISSUE #35: TopBar is missing menubar role
to fix, simply add `role="menubar"` [here](https://github.com/dequelabs/cauldron-react/blob/master/src/lib/composites/TopBar/TopBar.js#L96)

### PR DESCRIPTION
**Pull request by schne324**
(resolves #35)

### CODE REVIEW

File: src/lib/composites/TopBar/TopBar.js [hunk 1]
```diff
@@ -93,29 +95,27 @@ export default class TopBar extends Component {
...
-                  }
-                },
-                tabIndex: focusIndex === index ? 0 : -1,
-                menuItemRef: menuItem => {
-                  this.menuItems[index] = menuItem;
-
-                  if (child.props.menuItemRef) {
-                    child.props.menuItemRef(menuItem);
-                  }
+        <ul role="menubar">
```
Comment (schne324) [inline src/lib/composites/TopBar/TopBar.js]: the only real change is here: I added `role="menubar"`
