### PR TITLE
fix: passes additional props through to [role=dialog] element

### LINKED ISSUE #15: support passing event props (like 'onKeyDown') through to `<Modal />`

### PR DESCRIPTION
**Pull request by schne324**
resolves #15

### CODE REVIEW

File: src/lib/composites/Modal/index.js [hunk 1]
```diff
@@ -37,14 +33,14 @@ export default class Modal extends Component {
   componentWillReceiveProps(nextProps) {
     const { show } = nextProps;
 
-    if (show !== this.props.show) {
-      this.setState({ show }, () => {
-        if (!show) {
-          return this.close();
-        }
+    if (!show && this.props.show) {
```
Comment (stephenmathieson) [inline src/lib/composites/Modal/index.js]: This does not seem to be related to passing props thru to the `[role=dialog]` element. Was this committed by accident?

Comment (schne324) [reply src/lib/composites/Modal/index.js]: Not committed by accident but I will separate this `show` stuff into a separate pr
